name: Adapt README

on:
  pull_request:

jobs:
  adapt_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1
      - run: |
          julia  -e 'using Pkg; Pkg.add("Latexify"); Pkg.develop(path="."); include("src/create_README.jl")'
          echo $(git diff) 
      - name: Apply README change
        run: |
          CHANGED="$(git diff --name-only)"
          if [ ! -z $CHANGED ]; then
            >&2 echo "README needs to be updated"
            git commit -m "Update README" README.md 
            exit 1
          fi
